import { and, inArray, isNull } from 'drizzle-orm';
import { database } from '@db/connection.db';
import { task, TaskDTO } from '@db/tables/task.table';
import { User } from '@db/tables/user.table';
import { daysFromNow } from './utils.seed';

export async function seedTasks(seededUsers: { byEmail: Record<string, User> }, meetingByTitle: Record<string, any>) {
  const getUser = (email: string) => {
    const found = seededUsers.byEmail[email];
    if (!found) throw new Error(`Usuario no encontrado en seed: ${email}`);
    return found;
  };

  const taskValues: TaskDTO[] = [
    {
      meetingId: meetingByTitle['Diagnostico inicial de Textiles del Sur'].id,
      pymeId: getUser('pyme@hubsme.com').id,
      consultantId: getUser('consultor@hubsme.com').id,
      title: 'Crear tablero comercial compartido',
      description: 'Centralizar leads, oportunidades y cierres por vendedor.',
      assignedTo: 'pyme',
      priority: 'alta',
      status: 'completada',
      dueDate: daysFromNow(-18),
    },
    {
      meetingId: meetingByTitle['Diagnostico inicial de Textiles del Sur'].id,
      pymeId: getUser('pyme@hubsme.com').id,
      consultantId: getUser('consultor@hubsme.com').id,
      title: 'Propuesta de stack digital',
      description: 'Definir CRM, automatizaciones y flujo de reporte comercial.',
      assignedTo: 'consultor',
      priority: 'media',
      status: 'completada',
      dueDate: daysFromNow(-17),
    },
    {
      meetingId: meetingByTitle['Seguimiento de pipeline comercial'].id,
      pymeId: getUser('pyme@hubsme.com').id,
      consultantId: getUser('consultor@hubsme.com').id,
      title: 'Definir SLA de leads',
      description: 'Establecer tiempos maximos de contacto para nuevos leads.',
      assignedTo: 'pyme',
      priority: 'alta',
      status: 'en_progreso',
      dueDate: daysFromNow(2),
    },
    {
      meetingId: meetingByTitle['Seguimiento de pipeline comercial'].id,
      pymeId: getUser('pyme@hubsme.com').id,
      consultantId: getUser('consultor@hubsme.com').id,
      title: 'Workshop de forecast',
      description: 'Capacitar al equipo comercial en pronostico y seguimiento.',
      assignedTo: 'consultor',
      priority: 'media',
      status: 'pendiente',
      dueDate: daysFromNow(4),
    },
    {
      meetingId: meetingByTitle['Revision de indicadores de abril'].id,
      pymeId: getUser('pyme@hubsme.com').id,
      consultantId: getUser('consultor@hubsme.com').id,
      title: 'Actualizar score semanal de vendedores',
      description: 'Agregar conversion, ticket y tiempo de seguimiento al score comercial.',
      assignedTo: 'consultor',
      priority: 'media',
      status: 'pendiente',
      dueDate: daysFromNow(6),
    },
    {
      meetingId: meetingByTitle['Orden financiero trimestral'].id,
      pymeId: getUser('pyme@hubsme.com').id,
      consultantId: getUser('ana.torres@hubsme.com').id,
      title: 'Consolidar flujo de caja trimestral',
      description: 'Armar una vista de ingresos, egresos y necesidades de capital de trabajo.',
      assignedTo: 'pyme',
      priority: 'alta',
      status: 'pendiente',
      dueDate: daysFromNow(10),
    },
    {
      meetingId: meetingByTitle['Optimizacion de rutas y costos'].id,
      pymeId: getUser('contacto@tecnologistica.pe').id,
      consultantId: getUser('consultor@hubsme.com').id,
      title: 'Scorecard por ruta',
      description: 'Crear reporte semanal de costo, puntualidad y desvios por ruta.',
      assignedTo: 'consultor',
      priority: 'alta',
      status: 'completada',
      dueDate: daysFromNow(-13),
    },
    {
      meetingId: meetingByTitle['Optimizacion de rutas y costos'].id,
      pymeId: getUser('contacto@tecnologistica.pe').id,
      consultantId: getUser('consultor@hubsme.com').id,
      title: 'Clasificar desvios',
      description: 'Etiquetar causas raiz de desvios y documentarlas en operaciones.',
      assignedTo: 'pyme',
      priority: 'media',
      status: 'en_progreso',
      dueDate: daysFromNow(1),
    },
    {
      meetingId: meetingByTitle['Tablero de operaciones semanal'].id,
      pymeId: getUser('contacto@tecnologistica.pe').id,
      consultantId: getUser('roberto.sanchez@hubsme.com').id,
      title: 'Levantar tablero semanal de puntualidad',
      description: 'Seguimiento por OTIF, costo y alertas de capacidad.',
      assignedTo: 'consultor',
      priority: 'alta',
      status: 'pendiente',
      dueDate: daysFromNow(8),
    },
    {
      meetingId: meetingByTitle['Cierre de hallazgos operativos'].id,
      pymeId: getUser('contacto@tecnologistica.pe').id,
      consultantId: getUser('roberto.sanchez@hubsme.com').id,
      title: 'Normalizar tiempos de carga en sede norte',
      description: 'Reducir tiempos improductivos previos al despacho.',
      assignedTo: 'pyme',
      priority: 'media',
      status: 'bloqueada',
      dueDate: daysFromNow(16),
    },
    {
      meetingId: meetingByTitle['Rentabilidad por canal'].id,
      pymeId: getUser('gerencia@alimentospacifico.pe').id,
      consultantId: getUser('ana.torres@hubsme.com').id,
      title: 'Estado de resultados por canal',
      description: 'Separar ventas, costos y descuentos por canal comercial.',
      assignedTo: 'consultor',
      priority: 'alta',
      status: 'completada',
      dueDate: daysFromNow(-10),
    },
    {
      meetingId: meetingByTitle['Rentabilidad por canal'].id,
      pymeId: getUser('gerencia@alimentospacifico.pe').id,
      consultantId: getUser('ana.torres@hubsme.com').id,
      title: 'Revisar matriz de descuentos',
      description: 'Reducir descuentos de clientes con margen insuficiente.',
      assignedTo: 'pyme',
      priority: 'alta',
      status: 'en_progreso',
      dueDate: daysFromNow(3),
    },
    {
      meetingId: meetingByTitle['Growth plan retail moderno'].id,
      pymeId: getUser('gerencia@alimentospacifico.pe').id,
      consultantId: getUser('marco.paredes@hubsme.com').id,
      title: 'Definir promociones por canal moderno',
      description: 'Disenar calendario promocional con foco en rentabilidad.',
      assignedTo: 'consultor',
      priority: 'media',
      status: 'pendiente',
      dueDate: daysFromNow(9),
    },
    {
      meetingId: meetingByTitle['Control de costos de obra'].id,
      pymeId: getUser('operaciones@constructoranova.pe').id,
      consultantId: getUser('roberto.sanchez@hubsme.com').id,
      title: 'Reporte quincenal por obra',
      description: 'Levantar un tablero por obra con costos, avance y riesgos.',
      assignedTo: 'pyme',
      priority: 'alta',
      status: 'completada',
      dueDate: daysFromNow(-17),
    },
    {
      meetingId: meetingByTitle['Control de costos de obra'].id,
      pymeId: getUser('operaciones@constructoranova.pe').id,
      consultantId: getUser('roberto.sanchez@hubsme.com').id,
      title: 'Formato de compras criticas',
      description: 'Definir flujo de aprobacion y seguimiento para compras urgentes.',
      assignedTo: 'consultor',
      priority: 'media',
      status: 'pendiente',
      dueDate: daysFromNow(7),
    },
    {
      meetingId: meetingByTitle['Estructura de mandos medios'].id,
      pymeId: getUser('operaciones@constructoranova.pe').id,
      consultantId: getUser('elena.rivas@hubsme.com').id,
      title: 'Mapa de roles de jefatura',
      description: 'Clarificar alcance, responsabilidades y metricas de los mandos medios.',
      assignedTo: 'consultor',
      priority: 'media',
      status: 'pendiente',
      dueDate: daysFromNow(11),
    },
    {
      meetingId: meetingByTitle['Expansion comercial B2B'].id,
      pymeId: getUser('equipo@bioandesfoods.pe').id,
      consultantId: getUser('marco.paredes@hubsme.com').id,
      title: 'Pipeline B2B',
      description: 'Configurar fases y responsables para las cuentas de exportacion.',
      assignedTo: 'pyme',
      priority: 'alta',
      status: 'en_progreso',
      dueDate: daysFromNow(2),
    },
    {
      meetingId: meetingByTitle['Expansion comercial B2B'].id,
      pymeId: getUser('equipo@bioandesfoods.pe').id,
      consultantId: getUser('marco.paredes@hubsme.com').id,
      title: 'Secuencia outbound',
      description: 'Armar secuencia de emails y mensajes para prospectos internacionales.',
      assignedTo: 'consultor',
      priority: 'media',
      status: 'pendiente',
      dueDate: daysFromNow(6),
    },
    {
      meetingId: meetingByTitle['Modelo de demanda y stock'].id,
      pymeId: getUser('equipo@bioandesfoods.pe').id,
      consultantId: getUser('ana.torres@hubsme.com').id,
      title: 'Actualizar forecast trimestral',
      description: 'Refinar demanda proyectada por SKU y mercado.',
      assignedTo: 'pyme',
      priority: 'alta',
      status: 'bloqueada',
      dueDate: daysFromNow(14),
    },
    {
      meetingId: meetingByTitle['Experiencia de paciente omnicanal'].id,
      pymeId: getUser('direccion@clinicadentalorigen.pe').id,
      consultantId: getUser('valeria.soto@hubsme.com').id,
      title: 'Script comercial de primera llamada',
      description: 'Unificar preguntas, beneficios y cierre de primera llamada.',
      assignedTo: 'consultor',
      priority: 'alta',
      status: 'completada',
      dueDate: daysFromNow(-2),
    },
    {
      meetingId: meetingByTitle['Experiencia de paciente omnicanal'].id,
      pymeId: getUser('direccion@clinicadentalorigen.pe').id,
      consultantId: getUser('valeria.soto@hubsme.com').id,
      title: 'Tablero de no shows',
      description: 'Registrar inasistencias por sede y causa declarada.',
      assignedTo: 'pyme',
      priority: 'media',
      status: 'en_progreso',
      dueDate: daysFromNow(5),
    },
    {
      meetingId: meetingByTitle['Capacitacion de coordinadoras'].id,
      pymeId: getUser('direccion@clinicadentalorigen.pe').id,
      consultantId: getUser('elena.rivas@hubsme.com').id,
      title: 'Plan de onboarding para coordinadoras',
      description: 'Definir contenidos, evaluaciones y ritmo de entrenamiento.',
      assignedTo: 'consultor',
      priority: 'media',
      status: 'pendiente',
      dueDate: daysFromNow(9),
    },
    {
      meetingId: meetingByTitle['Ecommerce growth sprint'].id,
      pymeId: getUser('admin@ecosmartcommerce.pe').id,
      consultantId: getUser('marco.paredes@hubsme.com').id,
      title: 'Flujos de carrito abandonado',
      description: 'Activar secuencia de recuperacion en email y WhatsApp.',
      assignedTo: 'pyme',
      priority: 'alta',
      status: 'en_progreso',
      dueDate: daysFromNow(3),
    },
    {
      meetingId: meetingByTitle['Ecommerce growth sprint'].id,
      pymeId: getUser('admin@ecosmartcommerce.pe').id,
      consultantId: getUser('marco.paredes@hubsme.com').id,
      title: 'Roadmap CRO',
      description: 'Priorizar hipotesis de conversion para home, PDP y checkout.',
      assignedTo: 'consultor',
      priority: 'media',
      status: 'pendiente',
      dueDate: daysFromNow(8),
    },
    {
      meetingId: meetingByTitle['Automatizacion de reportes'].id,
      pymeId: getUser('admin@ecosmartcommerce.pe').id,
      consultantId: getUser('consultor@hubsme.com').id,
      title: 'Definir fuentes para dashboard ejecutivo',
      description: 'Mapear Shopify, Meta Ads y CRM hacia un tablero ejecutivo unico.',
      assignedTo: 'consultor',
      priority: 'alta',
      status: 'pendiente',
      dueDate: daysFromNow(13),
    },
    {
      meetingId: meetingByTitle['Mesa de seguimiento de rentabilidad'].id,
      pymeId: getUser('gerencia@alimentospacifico.pe').id,
      consultantId: getUser('consultor@hubsme.com').id,
      title: 'Armar minuta de rentabilidad mensual',
      description: 'Preparar formato recurrente de seguimiento comercial y financiero.',
      assignedTo: 'consultor',
      priority: 'media',
      status: 'pendiente',
      dueDate: daysFromNow(17),
    },
  ];

  const existingTasks = await database
    .select({ title: task.title })
    .from(task)
    .where(
      and(
        inArray(
          task.title,
          taskValues.map((item) => item.title),
        ),
        isNull(task.deletedAt),
      ),
    );
  const existingTaskTitles = new Set(existingTasks.map((item) => item.title));

  if (taskValues.some((item) => !existingTaskTitles.has(item.title))) {
    await database.insert(task).values(taskValues.filter((item) => !existingTaskTitles.has(item.title)));
  }
}
