import { Controller, Post, Body, Get, UseGuards, Request, Query, Header } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse, ApiBearerAuth } from '@nestjs/swagger';
import { HttpErrorDto } from '@core/dto/http-error.dto';
import { AuthService } from './auth.service';
import { LoginDto } from './dto/login.dto';
import { LoginResponseDto } from './dto/login-response.dto';
import { RegisterDto } from './dto/register.dto';
import { GoogleAuthUrlDto } from './dto/google-auth-url.dto';
import { GoogleAuthUrlResponseDto } from './dto/google-auth-url-response.dto';
import { GoogleCallbackQueryDto } from './dto/google-callback-query.dto';
import { JwtAuthGuard } from './jwt-auth.guard';
import { ForgotPasswordDto } from './dto/forgot-password.dto';
import { ResetPasswordDto } from './dto/reset-password.dto';
import { MessageResponseDto } from './dto/message-response.dto';

@ApiTags('auth')
@Controller('auth')
export class AuthController {
  constructor(private readonly authService: AuthService) {}

  @Post('login')
  @ApiOperation({ summary: 'User login' })
  @ApiResponse({ status: 200, type: LoginResponseDto })
  @ApiResponse({ status: 400, type: HttpErrorDto })
  async login(@Body() loginDto: LoginDto) {
    return await this.authService.login(loginDto);
  }

  @Post('register')
  @ApiOperation({ summary: 'Register a new PYME or consultant user' })
  @ApiResponse({ status: 200, type: LoginResponseDto })
  @ApiResponse({ status: 400, type: HttpErrorDto })
  async register(@Body() registerDto: RegisterDto) {
    return await this.authService.register(registerDto);
  }

  @Get('google/url')
  @ApiOperation({ summary: 'Get Google OAuth URL generated by backend' })
  @ApiResponse({ status: 200, type: GoogleAuthUrlResponseDto })
  @ApiResponse({ status: 400, type: HttpErrorDto })
  googleUrl(@Query() query: GoogleAuthUrlDto) {
    return this.authService.getGoogleAuthUrl(query);
  }

  @Get('google/callback')
  @Header('Content-Type', 'text/html')
  @ApiOperation({ summary: 'Google OAuth callback for popup login' })
  @ApiResponse({ status: 200, description: 'HTML response that posts the session to the opener window' })
  googleCallback(@Query() query: GoogleCallbackQueryDto) {
    return this.authService.handleGoogleCallback(query);
  }

  @Get('profile')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Get current user profile' })
  @ApiResponse({ status: 200, description: 'Returns current user information' })
  @ApiResponse({ status: 400, type: HttpErrorDto })
  getProfile(@Request() req) {
    return req.user;
  }

  @Post('forgot-password')
  @ApiOperation({ summary: 'Request password reset link via email' })
  @ApiResponse({ status: 200, type: MessageResponseDto })
  @ApiResponse({ status: 400, type: HttpErrorDto })
  async forgotPassword(@Body() forgotPasswordDto: ForgotPasswordDto) {
    return await this.authService.forgotPassword(forgotPasswordDto);
  }

  @Post('reset-password')
  @ApiOperation({ summary: 'Reset user password using token' })
  @ApiResponse({ status: 200, type: MessageResponseDto })
  @ApiResponse({ status: 400, type: HttpErrorDto })
  async resetPassword(@Body() resetPasswordDto: ResetPasswordDto) {
    return await this.authService.resetPassword(resetPasswordDto);
  }
}
