import { ApiProperty } from '@nestjs/swagger';

class MeetingRecordingOrganizerUserDto {
  @ApiProperty()
  id: string;

  @ApiProperty({ nullable: true })
  displayName: string | null;

  @ApiProperty()
  userIdentityType: string;

  @ApiProperty()
  tenantId: string;
}

class MeetingRecordingOrganizerDto {
  @ApiProperty({ nullable: true })
  application: unknown | null;

  @ApiProperty({ nullable: true })
  device: unknown | null;

  @ApiProperty({ type: MeetingRecordingOrganizerUserDto, nullable: true })
  user: MeetingRecordingOrganizerUserDto | null;
}

export class MeetingRecordingDto {
  @ApiProperty()
  id: string;

  @ApiProperty()
  meetingId: string;

  @ApiProperty()
  callId: string;

  @ApiProperty()
  contentCorrelationId: string;

  @ApiProperty()
  createdDateTime: Date;

  @ApiProperty()
  endDateTime: Date;

  @ApiProperty()
  recordingContentUrl: string;

  @ApiProperty({
    nullable: true,
    description: 'OneDrive/SharePoint browser URL for the recording file. It can still require Microsoft sign-in.',
  })
  webUrl: string | null;

  @ApiProperty({
    nullable: true,
    description: 'Anonymous read-only sharing URL for the recording file, when tenant sharing policy allows it.',
  })
  publicUrl: string | null;

  @ApiProperty({
    nullable: true,
    description: 'Short-lived preauthenticated download URL generated by Microsoft Graph for immediate playback.',
  })
  downloadUrl: string | null;

  @ApiProperty({ nullable: true })
  driveId: string | null;

  @ApiProperty({ nullable: true })
  driveItemId: string | null;

  @ApiProperty({ nullable: true })
  fileName: string | null;

  @ApiProperty({ type: MeetingRecordingOrganizerDto, nullable: true })
  meetingOrganizer: MeetingRecordingOrganizerDto | null;
}
